name: toggl_shortcut
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # localization
  intl: ^0.17.0

  # database
  firebase_core: ^1.20.0
  cloud_firestore: ^3.4.3

  # account authentication
  firebase_auth: ^3.7.0
  google_sign_in: ^5.2.1

  # router
  go_router: ^3.1.1

  # dependency
  injectable: ^1.5.3
  get_it: ^7.2.0

  # state management
  provider: ^6.0.3

  # http
  http: ^0.13.4

  # utility
  equatable: 2.0.3
  collection: ^1.15.0

  # design
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^1.11.5
  injectable_generator: "^1.2.0"

flutter:
  uses-material-design: true
  fonts:
    - family: MPLUSRounded1c
      fonts:
        - asset: assets/fonts/M_PLUS_Rounded_1c/MPLUSRounded1c-Thin.ttf
          weight: 100
        - asset: assets/fonts/M_PLUS_Rounded_1c/MPLUSRounded1c-Light.ttf
          weight: 300
        - asset: assets/fonts/M_PLUS_Rounded_1c/MPLUSRounded1c-Regular.ttf
          weight: 400
        - asset: assets/fonts/M_PLUS_Rounded_1c/MPLUSRounded1c-Medium.ttf
          weight: 500
        - asset: assets/fonts/M_PLUS_Rounded_1c/MPLUSRounded1c-Bold.ttf
          weight: 700
        - asset: assets/fonts/M_PLUS_Rounded_1c/MPLUSRounded1c-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/M_PLUS_Rounded_1c/MPLUSRounded1c-Black.ttf
          weight: 900